[project]
name = "lll-simple-ai-service"
version = "0.1.0"
description = "Structured AI service with Outlines for JSON output"
requires-python = ">=3.12"

[project.scripts]

[tool.taskipy.tasks]
dev = "set PYTHONDONTWRITEBYTECODE=1 && python scripts/start_service.py"